openapi: 3.0.1
info:
  title: Shopping API
  version: "1.0"
  description: API for managing categories and products in the shopping database.
servers:
  - url: http://localhost:7000
paths:
  /api/categories:
    get:
      summary: Get all categories
      tags:
        - Categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'
  /api/categories/{id}/products:
    get:
      summary: Get products by category ID
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of products in the category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
components:
  schemas:
    CategoryDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    ProductDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: decimal